services:
  - type: web
    name: digit-recognition
    env: python
    region: ohio
    plan: free
    buildCommand: pip install --upgrade setuptools wheel pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
